desktop app integration
livepeer/livepeer-swarm pull request #30
Opened 2017-04-19 03:32 UTC by ericxtang

Integration with the desktop app

* Get a stream ID before streaming the video

2017-04-19 14:07 UTC, dob requested changes

2017-04-19 14:07 UTC, dob commented on livepeer/streaming/streamer.go
> +	for k, _ := range self.hlsBuffers {
should this be `self.hlsBuffers` or `self.rtmpBuffers`?

2017-04-19 14:07 UTC, dob commented on livepeer/streaming/streamer.go
> +func (self *Streamer) GetAllNetworkStreams() []*lpmsStream.VideoStream {
What's a NetworkStream again?

2017-04-20 16:49 UTC, ericxtang commented on livepeer/streaming/streamer.go
> +func (self *Streamer) GetAllNetworkStreams() []*lpmsStream.VideoStream {
NetworkStream is the new stream concept.  We are phasing out of the old stream.  So now, streamer keeps track of "NetworkStreams", and they can be subscribed to via "HLSBuffer" or "RTMPBuffer".

2017-04-20 18:11 UTC, dob approved these changes
🚢

2017-04-20 18:11 UTC, merged